{"level":"error","message":"\nInvalid `prisma.user.findUnique()` invocation in\nC:\\Users\\Buzz brain\\Desktop\\haid\\src\\controllers\\authController.js:81:36\n\n  78 }\n  79 try {\n  80   const { email, password } = req.body;\n→ 81   const user = await prisma.user.findUnique(\nCan't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.","method":"POST","stack":"PrismaClientKnownRequestError: \nInvalid `prisma.user.findUnique()` invocation in\nC:\\Users\\Buzz brain\\Desktop\\haid\\src\\controllers\\authController.js:81:36\n\n  78 }\n  79 try {\n  80   const { email, password } = req.body;\n→ 81   const user = await prisma.user.findUnique(\nCan't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.\n    at ei.handleRequestError (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:121:7268)\n    at ei.handleAndLogRequestError (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:121:6593)\n    at ei.request (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:121:6300)\n    at async a (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:130:9551)\n    at async exports.login (C:\\Users\\Buzz brain\\Desktop\\haid\\src\\controllers\\authController.js:81:18)","timestamp":"2025-09-30T18:39:31.315Z","url":"/api/auth/login"}
{"clientVersion":"6.16.2","errorCode":"P1001","level":"error","message":"Prisma failed to connect: Can't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.","name":"PrismaClientInitializationError","stack":"PrismaClientInitializationError: Can't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.\n    at r (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:112:2770)","timestamp":"2025-09-30T19:02:19.476Z"}
{"clientVersion":"6.16.2","errorCode":"P1001","level":"error","message":"Prisma failed to connect: Can't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.","name":"PrismaClientInitializationError","stack":"PrismaClientInitializationError: Can't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.\n    at r (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:112:2770)","timestamp":"2025-09-30T19:03:27.174Z"}
{"clientVersion":"6.16.2","errorCode":"P1001","level":"error","message":"Prisma failed to connect: Can't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.","name":"PrismaClientInitializationError","stack":"PrismaClientInitializationError: Can't reach database server at `aws-1-us-west-1.pooler.supabase.com:5432`\n\nPlease make sure your database server is running at `aws-1-us-west-1.pooler.supabase.com:5432`.\n    at r (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:112:2770)","timestamp":"2025-09-30T19:05:32.733Z"}
{"clientVersion":"6.16.2","errorCode":"P1000","level":"error","message":"Prisma failed to connect: Authentication failed against database server, the provided database credentials for `postgres` are not valid.\n\nPlease make sure to provide valid database credentials for the database server at the configured address.","name":"PrismaClientInitializationError","stack":"PrismaClientInitializationError: Authentication failed against database server, the provided database credentials for `postgres` are not valid.\n\nPlease make sure to provide valid database credentials for the database server at the configured address.\n    at r (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:112:2770)","timestamp":"2025-09-30T19:16:34.852Z"}
{"clientVersion":"6.16.2","errorCode":"P1012","level":"error","message":"Prisma failed to connect: \u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:13\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m12 | \u001b[0m  provider = \"postgresql\"\n\u001b[1;94m13 | \u001b[0m  url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1","name":"PrismaClientInitializationError","stack":"PrismaClientInitializationError: \u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:13\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m12 | \u001b[0m  provider = \"postgresql\"\n\u001b[1;94m13 | \u001b[0m  url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1\n    at r (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:112:2770)","timestamp":"2025-09-30T19:22:12.065Z"}
{"clientVersion":"6.16.2","errorCode":"P1012","level":"error","message":"Prisma failed to connect: \u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:13\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m12 | \u001b[0m  provider = \"postgresql\"\n\u001b[1;94m13 | \u001b[0m  url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1","name":"PrismaClientInitializationError","stack":"PrismaClientInitializationError: \u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:13\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m12 | \u001b[0m  provider = \"postgresql\"\n\u001b[1;94m13 | \u001b[0m  url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1\n    at r (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:112:2770)","timestamp":"2025-09-30T19:53:28.510Z"}
{"clientVersion":"6.16.2","errorCode":"P1012","level":"error","message":"Prisma failed to connect: \u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:13\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m12 | \u001b[0m  provider = \"postgresql\"\n\u001b[1;94m13 | \u001b[0m  url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1","name":"PrismaClientInitializationError","stack":"PrismaClientInitializationError: \u001b[1;91merror\u001b[0m: \u001b[1mEnvironment variable not found: DATABASE_URL.\u001b[0m\n  \u001b[1;94m-->\u001b[0m  \u001b[4mschema.prisma:13\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\u001b[1;94m12 | \u001b[0m  provider = \"postgresql\"\n\u001b[1;94m13 | \u001b[0m  url      = \u001b[1;91menv(\"DATABASE_URL\")\u001b[0m\n\u001b[1;94m   | \u001b[0m\n\nValidation Error Count: 1\n    at r (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\@prisma\\client\\runtime\\library.js:112:2770)","timestamp":"2025-09-30T19:54:23.581Z"}
{"level":"error","message":"Event validation failed: hederaTx: Cast to string failed for value \"{\n  status: 'SUCCESS',\n  transactionId: '0.0.6928106@1759262942.203211621',\n  sequenceNumber: 50,\n  runningHash: '235,148,233,138,233,57,187,129,76,21,217,130,245,31,2,77,3,137,116,192,35,183,244,248,170,193,18,29,40,69,210,213,241,227,202,37,78,209,91,242,175,35,83,142,3,216,31,133'\n}\" (type Object) at path \"hederaTx\"","method":"POST","stack":"ValidationError: Event validation failed: hederaTx: Cast to string failed for value \"{\n  status: 'SUCCESS',\n  transactionId: '0.0.6928106@1759262942.203211621',\n  sequenceNumber: 50,\n  runningHash: '235,148,233,138,233,57,187,129,76,21,217,130,245,31,2,77,3,137,116,192,35,183,244,248,170,193,18,29,40,69,210,213,241,227,202,37,78,209,91,242,175,35,83,142,3,216,31,133'\n}\" (type Object) at path \"hederaTx\"\n    at Document.invalidate (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at model.$set (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:1480:12)\n    at model.$set (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:1132:16)\n    at model.Document (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:178:12)\n    at model.Model (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\model.js:127:12)\n    at new model (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\model.js:4834:15)\n    at exports.createEvent (C:\\Users\\Buzz brain\\Desktop\\haid\\src\\controllers\\eventController.js:45:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-09-30T20:09:09.404Z","url":"/api/events","user":"68dc38226cc1624c1061a347"}
{"level":"error","message":"AidLog validation failed: hederaTx: Cast to string failed for value \"{\n  status: 'SUCCESS',\n  transactionId: '0.0.6928106@1759263762.126750257',\n  sequenceNumber: 53,\n  runningHash: '141,53,151,15,103,17,156,140,88,192,208,226,142,91,0,202,233,162,142,225,58,242,74,211,182,21,171,246,3,210,7,21,152,141,235,97,36,69,143,249,235,195,84,134,0,129,190,151'\n}\" (type Object) at path \"hederaTx\"","method":"POST","stack":"ValidationError: AidLog validation failed: hederaTx: Cast to string failed for value \"{\n  status: 'SUCCESS',\n  transactionId: '0.0.6928106@1759263762.126750257',\n  sequenceNumber: 53,\n  runningHash: '141,53,151,15,103,17,156,140,88,192,208,226,142,91,0,202,233,162,142,225,58,242,74,211,182,21,171,246,3,210,7,21,152,141,235,97,36,69,143,249,235,195,84,134,0,129,190,151'\n}\" (type Object) at path \"hederaTx\"\n    at Document.invalidate (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:3358:32)\n    at model.$set (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:1480:12)\n    at model.$set (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:1132:16)\n    at model.Document (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\document.js:178:12)\n    at model.Model (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\model.js:127:12)\n    at new model (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\model.js:4834:15)\n    at C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\model.js:2775:20\n    at Array.map (<anonymous>)\n    at Function.create (C:\\Users\\Buzz brain\\Desktop\\haid\\node_modules\\mongoose\\lib\\model.js:2763:34)\n    at exports.scan (C:\\Users\\Buzz brain\\Desktop\\haid\\src\\controllers\\scanController.js:80:31)","timestamp":"2025-09-30T20:22:49.641Z","url":"/api/scans","user":"68dc3b91f173e81e7b1f7ade"}
{"level":"error","message":"Cast to ObjectId failed for value \"<aidLogId>\" (type string) at path \"_id\" for model \"AidLog\"","method":"GET","stack":"CastError: Cast to ObjectId failed for value \"<aidLogId>\" (type string) at path \"_id\" for model \"AidLog\"\n    at SchemaObjectId.cast (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\schema\\objectId.js:251:11)\n    at SchemaType.applySetters (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\schemaType.js:1258:12)\n    at SchemaType.castForQuery (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\schemaType.js:1694:17)\n    at cast (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\cast.js:390:32)\n    at Query.cast (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\query.js:5060:12)\n    at Query._castConditions (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\query.js:2374:10)\n    at model.Query._findOne (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\query.js:2697:8)\n    at model.Query.exec (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongoose\\lib\\query.js:4627:80)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async exports.verifyAidLog (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\src\\controllers\\verificationController.js:46:20)","timestamp":"2025-10-29T19:21:09.913Z","url":"/api/verify/aidlog/%3CaidLogId%3E"}
{"level":"error","message":"E11000 duplicate key error collection: haid-backend.users index: did_1 dup key: { did: null }","method":"POST","stack":"MongoServerError: E11000 duplicate key error collection: haid-backend.users index: did_1 dup key: { did: null }\n    at InsertOneOperation.execute (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongodb\\lib\\operations\\insert.js:51:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async tryOperation (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:207:20)\n    at async executeOperation (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:75:16)\n    at async Collection.insertOne (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\mongodb\\lib\\collection.js:157:16)","timestamp":"2025-10-30T08:53:07.277Z","url":"/api/auth/v2/register"}
{"level":"error","message":"receipt for transaction 0.0.6928106@1761814713.510059338 contained error status INSUFFICIENT_ACCOUNT_BALANCE","method":"POST","stack":"StatusError: receipt for transaction 0.0.6928106@1761814713.510059338 contained error status INSUFFICIENT_ACCOUNT_BALANCE\n    at new ReceiptStatusError (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\@hashgraph\\sdk\\lib\\ReceiptStatusError.cjs:36:5)\n    at TransactionReceiptQuery._mapStatusError (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\@hashgraph\\sdk\\lib\\transaction\\TransactionReceiptQuery.cjs:265:12)\n    at TransactionReceiptQuery.execute (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\@hashgraph\\sdk\\lib\\Executable.cjs:682:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async TransactionResponse.getReceipt (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\node_modules\\@hashgraph\\sdk\\lib\\transaction\\TransactionResponse.cjs:84:17)\n    at async transferHbar (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\src\\utils\\hederaAccount.js:45:19)\n    at async exports.donateHbar (C:\\Users\\Buzz brain\\Desktop\\Current Development\\haid-backend\\src\\controllers\\donationController.js:27:22)","timestamp":"2025-10-30T08:58:42.153Z","url":"/api/donations/hbar","user":"6903256f7923e206767808c4"}
